title: elkokito
description: much wow
markdown: kramdown

remote_theme: jekyll/minima

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-remote-theme

minima:
  skin: dark

permalink: /:categories/:title/

collections:
  bubbletea:
    output: true
    permalink: /bubbletea/:title
  golang:
    output: true
    permalink: /golang/:title

feed:
  collections:
    - bubbletea
    - golang
