title: elkokito
description: reading
markdown: kramdown

plugins:
  - jekyll-sitemap
  - jekyll-feed

permalink: /:categories/:title/

collections:
  bubbletea:
    output: true
    permalink: /bubbletea/:title

feed:
  collections:
    - bubbletea
